### ISSUE TITLE
Task lists not checked / unchecked with Alt + C if they have more than one space after "-"

### ISSUE THREAD

**Issue by jgoulet1994** [neilsustc/vscode-markdown#361]
#### What is the problem?
Task lists are not checked / unchecked with Alt + c with multiple spaces between " - " and " [ ] ".  See steps to reproduce as an example.

##### Not working:
**NOTE**: Spaces in Github are removed.  Therefore, I am using "\_" to denote spaces.
-\_\_\_[ ] item 1 
*Alt + C to check task*
-\_\_\_[ ] item 1 (no changes)

##### Expected Results 
-\_\_\_[ ] item 1
*Alt+C to check task*
-\_\_\_[x] item 1

What works:
\- [ ] item 1
*Alt + C to check task*
\- [x] item 1 (working as expected)

#### Is there any error message in the console?
N/A

**Comment by neilsustc** [comment]
Should be fixed in the [dev build](https://github.com/neilsustc/vscode-markdown#latest-development-build).

**Comment by AskoldMakaruk** [comment]
Still an issue with this:
won't be toggled by *Alt+c*
`- - [x] Item`
This will
`- [x] Item`

**Comment by yzhang-gh** [comment]
@AskoldMakaruk This is a different issue. I would suggest using `- [ ] item` before we get a fix.
`- - [ ] item` looks weird... although it does work.
